# Generated by Django 2.1.2 on 2018-11-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('HouseSearch', '0008_auto_20181113_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.CharField(
                choices=[('PH', 'Private house'), ('AP', 'Apartment'), ('VL', 'Villa'), ('BN', 'Bungalow'),
                         ('CT', 'Cottage')], default='PH', max_length=2),
        ),
    ]
