# Generated by Django 2.1.2 on 2018-11-15 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('UserProfile', '0011_userinfo_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='note',
            new_name='parent',
        ),
    ]
