# Generated by Django 2.1.2 on 2018-11-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserProfile', '0019_auto_20181120_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='last_visit',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='registration',
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='big_photo',
            field=models.ImageField(blank=True, upload_to='user_photo/'),
        ),
    ]
