# Generated by Django 2.1.2 on 2018-11-25 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('UserProfile', '0021_auto_20181124_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
